# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', max_length=254, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
