# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Map')),
            ],
        ),
    ]
