# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='owner',
            new_name='author',
        ),
    ]
