# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_version_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
